<img src="https://imgur.com/dbHJUg0.png" style="float:center;">

Analisamos no notebook anterior conjuntos de dados unidimensionais. Ao longo do caminho, introduzimos o loop `for` e a declarações condicionais. Vamos estender nossa discussão para arrays bidimensionais e números aleatórios.

# <font color=#005757>1. Arrays bidimensionais </font>

Um **array bidimensional** é como uma matriz, representando uma grade de valores organizados em linhas e colunas. Por outro lado, um **array unidimensional** é como uma matriz linha ou coluna, representando uma lista ou sequência de valores dispostos em uma única dimensão.

<div>
<img src="https://imgur.com/McfnVbG.png" width="900"/>
</div>




## <font color=#005757>1.1 Criando arrays 2D e visualizando sua dimensão</font>

Muitas das funções que usamos para criar arrays unidimensionais podem ser usadas para criar arrays bidimensionais:


In [ ]:
import numpy as np

# Lista dentro de uma lista e depois transformando em np.array:
dados = np.array([
    [7.9, 7.1, 5.7, 3.6, 2.3, 1.7],
    [9.9, 8.5, 7.4, 5.7, 4.9, 4.5],
    [12.8, 10.7, 8.8, 4.0, 2.1, 1.0]
])

# Vamos visualizar!
dados

array([[ 7.9,  7.1,  5.7,  3.6,  2.3,  1.7],
       [ 9.9,  8.5,  7.4,  5.7,  4.9,  4.5],
       [12.8, 10.7,  8.8,  4. ,  2.1,  1. ]])

Podemos visualizar a dimensão desse array usando `np.shape` onde retorna uma tupla de forma nos diz quantas linhas e colunas existem no array:

In [ ]:
dimensao = np.shape(dados)
dimensao

(3, 6)

In [ ]:
# Número de linnhas
dimensao[0]

3

In [ ]:
# Número de colunas
dimensao[1]

6

Para criar um array bidimensional preenchido com uns, podemos usar a função `ones` do NumPy da mesma maneira que `zeros`:

In [ ]:
# 3 linhas com 6 colunas
np.ones((3, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
# 5 linhas com 5 colunas
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Criamos arrays unidimensionais de valores regularmente incrementados usando a função `arange` do NumPy. Não há uma versão bidimensional de `arange`, mas podemos realizar algo semelhante criando um array unidimensional usando `arange` e depois usando a função `reshape` do NumPy para remodelar esse array em um array bidimensional:

In [ ]:
# Isso é array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
dados_regulares = np.arange(12)

# Aqui pegamos e modificamos para 2 linhas e 6 colunas
dados_regulares = np.reshape(dados_regulares, (2, 6))
dados_regulares

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

## <font color=#005757>1.2 Acessando e fatiando um array 2D </font>

A sintaxe para acessar e fatiar subarrays em um array bidimensional é muito semelhante ao que é feito em listas e arrays unidimensionais. A diferença em todos esses casos é que, em vez de especificar valores de índice para uma dimensão, precisamos especificá-los para duas dimensões. Os valores de índice para cada dimensão são separados por uma vírgula nos colchetes após o nome do array:


In [ ]:
# Veja nossos dados que criamos no início do notebook:
dados

array([[ 7.9,  7.1,  5.7,  3.6,  2.3,  1.7],
       [ 9.9,  8.5,  7.4,  5.7,  4.9,  4.5],
       [12.8, 10.7,  8.8,  4. ,  2.1,  1. ]])

In [ ]:
# Linha de índice 1 e coluna de índice 2
dados[1,2]

7.4

In [ ]:
# Quero da segunda linha em diante, mas só até a segunda coluna
dados[1:,:2]

array([[ 9.9,  8.5],
       [12.8, 10.7]])

In [ ]:
# Quero só a primeira linha, mas da terceira coluna pra frente
dados[:1, 2:]

array([[5.7, 3.6, 2.3, 1.7]])

## <font color=#005757>1.3. Cálculos com arrays 2D</font>

Como vimos nos notebooks anteriores, conseguimos:

1.   operar elemento a elemento em arrays unidimensionais,
2.   aplicar uma função elemento a elemento em arrays unidimensionais,
3.   usar uma função para fazer um cálculo que considere todos os elementos em um array, sem usar loops

O mesmo vale para arrays bidimensionais:  



In [ ]:
# Veja nossos dados que criamos no início do notebook:
dados

array([[ 7.9,  7.1,  5.7,  3.6,  2.3,  1.7],
       [ 9.9,  8.5,  7.4,  5.7,  4.9,  4.5],
       [12.8, 10.7,  8.8,  4. ,  2.1,  1. ]])

In [ ]:
dados_ao_quadrado = dados ** 2
dados_ao_quadrado

array([[ 62.41,  50.41,  32.49,  12.96,   5.29,   2.89],
       [ 98.01,  72.25,  54.76,  32.49,  24.01,  20.25],
       [163.84, 114.49,  77.44,  16.  ,   4.41,   1.  ]])

In [ ]:
dados_seno = np.sin(dados)
dados_seno

array([[ 0.99894134,  0.72896904, -0.55068554, -0.44252044,  0.74570521,
         0.99166481],
       [-0.45753589,  0.79848711,  0.8987081 , -0.55068554, -0.98245261,
        -0.97753012],
       [ 0.23150983, -0.95663502,  0.58491719, -0.7568025 ,  0.86320937,
         0.84147098]])

In [ ]:
np.min(dados_seno)

-0.9824526126243325

## <font color=#005757>1.4. Laços de repetição aninhados</font>

Para matrizes bidimensionais, um único laço de repetição não pode percorrer diretamente todos os elementos do array. Mas, usando dois laços de repetição, um dentro do outro - aninhando os laços - podemos percorrer todos os índices de linha e, para cada índice de linha, todos os índices de coluna, para acessar todas as combinações possíveis de índices de linha e coluna na matriz:

In [ ]:
# Veja nossos dados que criamos no início do notebook:
dados

array([[ 7.9,  7.1,  5.7,  3.6,  2.3,  1.7],
       [ 9.9,  8.5,  7.4,  5.7,  4.9,  4.5],
       [12.8, 10.7,  8.8,  4. ,  2.1,  1. ]])

In [ ]:
for linha in range(np.shape(dados)[0]):
  for coluna in range(np.shape(dados)[1]):
    print(f"(i, j) = {linha, coluna} valor: {dados[linha, coluna]}")

(i, j) = (0, 0) valor: 7.9
(i, j) = (0, 1) valor: 7.1
(i, j) = (0, 2) valor: 5.7
(i, j) = (0, 3) valor: 3.6
(i, j) = (0, 4) valor: 2.3
(i, j) = (0, 5) valor: 1.7
(i, j) = (1, 0) valor: 9.9
(i, j) = (1, 1) valor: 8.5
(i, j) = (1, 2) valor: 7.4
(i, j) = (1, 3) valor: 5.7
(i, j) = (1, 4) valor: 4.9
(i, j) = (1, 5) valor: 4.5
(i, j) = (2, 0) valor: 12.8
(i, j) = (2, 1) valor: 10.7
(i, j) = (2, 2) valor: 8.8
(i, j) = (2, 3) valor: 4.0
(i, j) = (2, 4) valor: 2.1
(i, j) = (2, 5) valor: 1.0


# <font color=#005757>2. Números aleatórios</font>

Até o momento, fizemos vários cálculos de situações que se enquadrariam como
**modelos determinísticos**, isto é, situações em que o estado das variáveis sendo modeladas é completamente calculado usando o estado do modelo em um momento anterior. Assim, dadas as mesmas condições iniciais - os valores das variáveis sendo modeladas no tempo zero - os estados futuros calculados pelo modelo sempre serão os mesmos.

No entanto, existem **modelos não determinísticos**, onde o estado anterior (ou inicial) das variáveis sendo modeladas não define (ou determina) completamente o estado posterior dessas variáveis. Há algum elemento de **aleatoriedade** no modelo de modo que cada vez que o modelo é executado, mesmo que as condições iniciais sejam as mesmas, os valores calculados das variáveis do modelo serão diferentes. Isso tem aplicações que vão desde o movimento browniano até os preços do mercado de ações.

Para criar um modelo não determinístico em um computador, precisamos de uma maneira de gerar **números aleatórios**. Na natureza, fenômenos físicos como estados quânticos exibem comportamento aleatório. No entanto, um computador, por sua própria natureza, é determinístico:



In [ ]:
2 + 3

5

Enquanto os computadores são determinísticos, certos algoritmos matemáticos podem criar uma sequência de números que parece ser aleatória, embora os algoritmos estejam criando uma sequência periódica de números (ou seja, uma sequência que eventualmente se repetirá). As funções que utilizam esses algoritmos são chamadas de **geradores de números aleatórios** (ou, mais apropriadamente, "geradores de números **pseudoaleatórios**"). O período de repetição para o gerador de números aleatórios de um computador moderno é tão longo que, para muitas aplicações, podemos tratá-lo como um verdadeiro gerador de números aleatórios.

Por exemplo, a função `random` do módulo `random` usa um algoritmo chamado [Mersenne Twister](https://docs.python.org/3/library/random.html), que tem um período de repetição de $2^{19937−1}$, que, embora inadequado para criptografia, é longo o suficiente para muitas aplicações científicas e de engenharia.

Sequências de números aleatórios são controladas pelo **valor de semente do gerador**:


In [38]:
# Isso não retorna nada, mas fixa uma semente de aleatoriedade!
np.random.seed(42)

# Valores aleatórios entre 0 e 1 (não incluído)
np.random.uniform(size = 10)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [40]:
# Vamos mudar a semente (pode rodar mil vezes que vai ser sempre os mesmos valores)
np.random.seed(111)

# Valores aleatórios entre 0 e 1 (não incluído)
np.random.uniform(size = 10)

array([0.61217018, 0.16906975, 0.43605902, 0.76926247, 0.2953253 ,
       0.14916296, 0.02247832, 0.42022449, 0.23868214, 0.33765619])

O submódulo `random` do NumPy contém várias [funções diferentes](https://numpy.org/doc/stable/reference/random/legacy.html) que produzirão valores aleatórios seguindo várias distribuições estatísticas:

In [41]:
# Inteiros aleatórios entre 2 e 5 (não incluído)
np.random.randint(2, 5, size = 10)

array([4, 4, 3, 4, 2, 3, 2, 4, 4, 2])

In [42]:
# Uma matriz!
np.random.randint(-3, 2, size=(4,3))

array([[-3, -1,  0],
       [ 1,  0, -2],
       [-1,  0, -2],
       [ 0, -3,  1]])

# <font color=#005757>3. Exercícios </font>


## <font color=#005757>3.1 Andar aleatório do rato</font>
